# Generated by Django 2.2.19 on 2025-10-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0007_auto_20250702_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='chairman',
            field=models.CharField(help_text='Введите ФИО председатель', max_length=200, verbose_name='Председатель ЭКЗ комиссии'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='org_name',
            field=models.CharField(help_text='Введите навзвание образовательной организации', max_length=200, verbose_name='Название образовательной организации'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='qualification',
            field=models.CharField(help_text='Напишите квалификацию', max_length=100, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='reg_number',
            field=models.CharField(help_text='Введите регистрационный номер', max_length=10, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='ser_number',
            field=models.CharField(help_text='Введите номер серии', max_length=15, verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='speciality',
            field=models.CharField(help_text='Введите специальность', max_length=100, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='student_name',
            field=models.CharField(help_text='ФИО', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='supervisor',
            field=models.CharField(help_text='Введите ФИО руководителя', max_length=200, verbose_name='Руководитель'),
        ),
    ]
